apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagesize
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-watcher
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-nodes-global
subjects:
- kind: ServiceAccount
  name: imagesize
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: imagesize-controller
  name: imagesize-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagesize-controller
  template:
    metadata:
      labels:
        app: imagesize-controller
    spec:
      serviceAccountName: imagesize
      containers:
      - image: docker.io/kmjayadeep/imagesize-controller
        name: controller
