apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: simplecontroller
build:
  artifacts:
  - image: docker.io/kmjayadeep/imagesize-controller
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - deployment.yaml
